services:
  adplace:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 23045:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5423
      - DATABASE_NAME=adPlace
      - DATABASE_USER=adplace_backend
      - DATABASE_PASSWORD=mypassword
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=adPlace
      - POSTGRES_USER=adplace_backend
      - POSTGRES_PASSWORD=mypassword
    restart: always
    ports:
      - 5432:5432
volumes:
  dbdata:
    driver: local
