services:
  adplace:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 23045:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    restart: always
    ports:
      - 2500:5432
volumes:
  dbdata:
    driver: local
